language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
before_install:
  - npm install -g npm gally
install:
  - npm install
node_js:
  - '9'
  - '8'
  - '8.10'
script:
  - npm test
after_success:
  - ga promote $TRAVIS_BRANCH
  - npm run coveralls
  - npm run semantic-release
